### ISSUE TITLE
Warnings in Transactional Email page prior to key installation

### ISSUE THREAD

**Issue by netcarver** [ttttim0709/WireMailBrevo#1]
@ttttim0709 Hi there - thanks again for this module. With reference to the Transactional Email process module included with it...

![image](https://github.com/ttttim0709/WireMailBrevo/assets/16049/c1a083ee-04f2-424c-bf08-b327fc768d45)

1. There are some warnings due to attempt to iterate over empty [events data](https://github.com/ttttim0709/WireMailBrevo/blob/fcd079cfdec25494a335c2cc983b2d9166653874/ProcessWireMailBrevo.module#L71). This only occurs prior to setting the credentials in the main module.
2. (Request): Could the "Transactional Email" menu item be moved under the existing "Setup" top-level item?
3. (Request): Could the "No donors found" message be changed to something more meaningful - or be made translatable?

**Comment by ttttim0709** [comment]
@netcarver Hi, I just Made some changes to remove the warnings when the API Key is not set. And changed some other small things like adding permissions.

I personally like it as a separate tab but you can move the page from the admin parent to the setup parent

**Comment by netcarver** [comment]
@ttttim0709 Nice update, thank you, Timothy.
